name: protobuf_builder
environment:
  sdk: '>=2.10.0 <3.0.0'
dependencies:
  build: ^2.0.0
  protoc_plugin: any
dev_dependencies:
  build_runner: ^2.0.0
dependency_overrides:
  dart_style: ^2.0.0
  protoc_plugin:
    path: ../protoc_plugin
